config/routes.rb
Megatombike::Application.routes.draw do
  get "mobile_version" => "subscribe#force_mobile"
  get "full_version" => "subscribe#force_full"

  get "payments" => "payments#index"
  post "payments/set_paid/:team_id" => "payments#set_paid"
  post "payments/set_unpaid/:team_id" => "payments#set_unpaid"

  get "results/new" => "results#new"
  get "authentications" => "authentication#index"
  delete "authentications/:id" => "authentication#destroy"
  match "auth/:provider/callback" => "authentication#create"
  match "auth/failure" => "authentication#failure"
  post "authentications/use_this" => "authentication#use_this"

  post "results/create/:race_id" => "results#create"
  get "results/:race_id" => "results#index"
  get "results" => "results#index"
  
  resources :my_teams, :only => [:index]
  get "my_teams/:team_id/race/:race_id" => "my_teams#show"
  get "my_teams/:team_id" => "my_teams#show"

  get "teams/filter_period/:period_id" => "teams#filter_period"

  post "race_teams/add_rider"
  post "race_teams/remove_rider"
  post "race_teams/update_chosen"
 
  match "race_teams/new/:team_id/race/:race_id/:rdtmt" => "race_teams#new", :via => :get
  match "race_teams/new/:team_id/race/:race_id" => "race_teams#new", :via => :get
  match "race_teams/:team_id/race/:race_id/:rdtmt" => "race_teams#create", :via => :post
  match "race_teams/:team_id/race/:race_id" => "race_teams#create", :via => :post

  resources :race_teams, :only => [:edit,:update,:index, :destroy]
  resources :categories
  resources :races

  get "teams/filter_twt"
  get "teams/filter_fb"
  post "teams/add_rider"
  post "teams/remove_rider"

  post "riders/result_search"
  post "riders/search"
  get "subscribe/index"
  get "subscribe/finished"
  get "subscribe/reglement"

  resources :riders
  resources :cycling_teams
  resources :teams, :only => [:index, :new, :create, :destroy, :show]

  devise_for :users, :controllers => { :registrations => "registrations" }

  root :to => 'subscribe#index'

end

app/models/cycling_team.rb
class CyclingTeam < ActiveRecord::Base
  attr_accessible :name, :short_name, :active
  
  has_many :riders

  validates :name, :presence => true
  validates :short_name, :presence => true
end

app/controllers/cycling_teams_controller.rb
class CyclingTeamsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin, :only => [:new, :create, :edit,:update,:destroy]

  def index
    @cycling_teams = CyclingTeam.all
  end

  def show
    @cycling_team = CyclingTeam.find(params[:id])
  end

  def new
    @cycling_team = CyclingTeam.new
  end

  def create
    @cycling_team = CyclingTeam.new(params[:cycling_team])
    if @cycling_team.save
      redirect_to @cycling_team, :notice => "Successfully created cycling team."
    else
      render :action => 'new'
    end
  end

  def edit
    @cycling_team = CyclingTeam.find(params[:id])
  end

  def update
    @cycling_team = CyclingTeam.find(params[:id])
    if @cycling_team.update_attributes(params[:cycling_team])
      redirect_to @cycling_team, :notice  => "Successfully updated cycling team."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @cycling_team = CyclingTeam.find(params[:id])
    @cycling_team.destroy
    redirect_to cycling_teams_url, :notice => "Successfully destroyed cycling team."
  end
end

app/helpers/cycling_teams_helper.rb
module CyclingTeamsHelper
end

app/views/cycling_teams/_form.html.erb
<%= form_for @cycling_team do |f| %>
  <%= render :partial => "shared/validation_errors", :locals => {:model => @cycling_team} %> 

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :short_name %><br />
    <%= f.text_field :short_name %>
  </p>
  <p>
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/cycling_teams/edit.html.erb
<% title "Edit Cycling Team" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @cycling_team %> |
  <%= link_to "View All", cycling_teams_path %>
</p>

app/views/cycling_teams/index.html.erb
<% title "Cycling Teams" %>

<table>
  <tr>
    <th>Name</th>
    <th>Short Name</th>
    <th>Active</th>
  </tr>
  <% for cycling_team in @cycling_teams %>
    <tr>
      <td><%= cycling_team.name %></td>
      <td><%= cycling_team.short_name %></td>
      <td><%= cycling_team.active %></td>
      <td><%= link_to "Show", cycling_team %></td>
      <td><%= link_to "Edit", edit_cycling_team_path(cycling_team) %></td>
      <td><%= link_to "Destroy", cycling_team, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Cycling Team", new_cycling_team_path %></p>

app/views/cycling_teams/new.html.erb
<% title "New Cycling Team" %>

<%= render 'form' %>

<p><%= link_to "Back to List", cycling_teams_path %></p>

app/views/cycling_teams/show.html.erb
<% title "Cycling Team" %>

<p>
  <strong>Name:</strong>
  <%= @cycling_team.name %>
</p>
<p>
  <strong>Short Name:</strong>
  <%= @cycling_team.short_name %>
</p>
<p>
  <strong>Active:</strong>
  <%= @cycling_team.active %>
</p>

<p>
  <%= link_to "Edit", edit_cycling_team_path(@cycling_team) %> |
  <%= link_to "Destroy", @cycling_team, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", cycling_teams_path %>
</p>