config/routes.rb
Megatombike::Application.routes.draw do
  get "mobile_version" => "subscribe#force_mobile"
  get "full_version" => "subscribe#force_full"

  get "payments" => "payments#index"
  post "payments/set_paid/:team_id" => "payments#set_paid"
  post "payments/set_unpaid/:team_id" => "payments#set_unpaid"

  get "results/new" => "results#new"
  get "authentications" => "authentication#index"
  delete "authentications/:id" => "authentication#destroy"
  match "auth/:provider/callback" => "authentication#create"
  match "auth/failure" => "authentication#failure"
  post "authentications/use_this" => "authentication#use_this"

  post "results/create/:race_id" => "results#create"
  get "results/:race_id" => "results#index"
  get "results" => "results#index"
  
  resources :my_teams, :only => [:index]
  get "my_teams/:team_id/race/:race_id" => "my_teams#show"
  get "my_teams/:team_id" => "my_teams#show"

  get "teams/filter_period/:period_id" => "teams#filter_period"

  post "race_teams/add_rider"
  post "race_teams/remove_rider"
  post "race_teams/update_chosen"
 
  match "race_teams/new/:team_id/race/:race_id/:rdtmt" => "race_teams#new", :via => :get
  match "race_teams/new/:team_id/race/:race_id" => "race_teams#new", :via => :get
  match "race_teams/:team_id/race/:race_id/:rdtmt" => "race_teams#create", :via => :post
  match "race_teams/:team_id/race/:race_id" => "race_teams#create", :via => :post

  resources :race_teams, :only => [:edit,:update,:index, :destroy]
  resources :categories
  resources :races

  get "teams/filter_twt"
  get "teams/filter_fb"
  post "teams/add_rider"
  post "teams/remove_rider"

  post "riders/result_search"
  post "riders/search"
  get "subscribe/index"
  get "subscribe/finished"
  get "subscribe/reglement"

  resources :riders
  resources :cycling_teams
  resources :teams, :only => [:index, :new, :create, :destroy, :show]

  devise_for :users, :controllers => { :registrations => "registrations" }

  root :to => 'subscribe#index'

end

app/models/race.rb
class Race < ActiveRecord::Base
  SUBSCRIBE_UNTIL = 6 #ID of the race

  belongs_to :period
  belongs_to :category
  belongs_to :race
  has_many :races
  has_many :race_teams
  has_many :race_results
  has_many :team_results

  validates :name, :presence => true
  validates :previous_winner, :presence => true
  validates :category, :presence => true

  def display_name
    unless race.nil?
      return "#{race.name} > #{name}"
    end
    return name
  end

  def can_make_race_team?
    date >= Time.zone.now
  end

  def possible_to_make_race_team(races, race_teams)
    return false unless can_make_race_team?
    has_no_overlapping_race = races.index { |other_race| other_race.id != self.id and other_race.overlaps_with(self) and other_race.starts_before(self) }.nil?
    if has_no_overlapping_race
      return true
    else
      return (race_teams.empty? or race_teams.first.race_id == self.id)
    end
  end
  
  def possible_to_make_race_team_without_date_check(races, race_teams)
    has_no_overlapping_race = races.index { |other_race| other_race.id != self.id and other_race.overlaps_with(self) and other_race.starts_before(self) }.nil?
    if has_no_overlapping_race
      return true
    else
      return (race_teams.empty? or race_teams.first.race_id == self.id)
    end
  end

  def starts_before(other_race)
    other_race.date > self.date
  end

  def overlaps_with(other_race)
    (Race.date_between(other_race.date,date,end_date) or Race.date_between(other_race.end_date,date,end_date)) 
  end
  
  def latest_stage
    return nil if (is_tour == false or races.empty?)
    return races.select {|stage| stage.results_ready }.sort{ |x,y| y.date <=> x.date }.first
  end  

  def get_previous_race
    # get previous race
    previous_race = Race.where("date < :date AND race_id IS :race_id",{:date => date, :race_id => nil}).order("date DESC").first
    return nil if previous_race.nil?
    # check if results ready
    return previous_race if previous_race.results_ready
    # if not check if is tour and if it has a stage with results ready
    if previous_race.is_tour
      finished_stages = Race.where("race_id = :race_id AND results_ready = :rr",{:race_id => previous_race.id, :rr => true})
      return previous_race unless finished_stages.empty?
    end
    # else no previous race
    return nil
  end

  def get_next_race
    # get next race
    next_race = Race.where("date > :date AND race_id IS :race_id",{:date => date, :race_id => nil}).order("date ASC").first
    return nil if next_race.nil?
    # check if results ready
    return next_race if next_race.results_ready
    # if not check if is tour and if it has a stage with results ready
    if next_race.is_tour
      finished_stages = Race.where("race_id = :race_id AND results_ready = :rr",{:race_id => next_race.id, :rr => true})
      return next_race unless finished_stages.empty?
    end
    # else no previous race
    return nil
  end
  
  def self.all_except_stages
    return Race.where(race_id: nil).all
  end
  
  def self.editable_races(races, race_teams)
    editable_races = races.reject { |race| not race.possible_to_make_race_team(races, race_teams) }
  end

  def self.first_possible_race
   self.where("date > :now", {:now => Time.zone.now}).order("date ASC").first
  end
  
  def self.can_subscribe?
    self.where(id: SUBSCRIBE_UNTIL).first.date >= Time.zone.now
  end
  
  def self.latest_available_result
    race = self.where(results_ready: true).order("races.end_date DESC").first
  end

  private
  def self.date_between(other_date,begin_date,end_date)
    (other_date >= begin_date and other_date <= end_date)
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin, :only => [:show, :new, :create, :edit,:update,:destroy]

  # GET /races
  # GET /races.json
  def index
    @races = Race.where(race_id: nil).includes(:category).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @races }
    end
  end

  # GET /races/1
  # GET /races/1.json
  def show
    @race = Race.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @race }
    end
  end

  # GET /races/new
  # GET /races/new.json
  def new
    @race = Race.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @race }
    end
  end

  # GET /races/1/edit
  def edit
    @race = Race.find(params[:id])
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(params[:race])

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, notice: 'Race was successfully created.' }
        format.json { render json: @race, status: :created, location: @race }
      else
        format.html { render action: "new" }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /races/1
  # PUT /races/1.json
  def update
    @race = Race.find(params[:id])

    respond_to do |format|
      if @race.update_attributes(params[:race])
        format.html { redirect_to @race, notice: 'Race was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race = Race.find(params[:id])
    @race.destroy

    respond_to do |format|
      format.html { redirect_to races_url }
      format.json { head :ok }
    end
  end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/_form.html.erb
<%= form_for(@race) do |f| %>
  <%= render :partial => "shared/validation_errors", :locals => {:model => @race} %> 

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field datetime">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field datetime">
    <%= f.label :end_date %><br />
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :is_tour %><br />
    <%= f.check_box :is_tour %>
  </div>
  <div class="field">
    <%= f.label :previous_winner %><br />
    <%= f.text_field :previous_winner %>
  </div>
  <div class="field">
    <%= f.label :race_id %><br />
    <%= f.collection_select(:race_id, Race.where(is_tour:true).all, :id, :name, :prompt => 'Selecteer ...') %>
  </div>
 <div class="field">
    <%= f.label :category_id %><br />
    <%= f.collection_select(:category_id, Category.all, :id, :name, :prompt => 'Selecteer ...') %>
  </div>
  <div class="field">
    <%= f.label :results_ready %><br />
    <%= f.check_box :results_ready %>
  </div>
  <div class="field">
    <%= f.label :team_time_trial %><br />
    <%= f.check_box :team_time_trial %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/races/edit.html.erb
<h1>Editing race</h1>

<%= render 'form' %>

<%= link_to 'Show', @race %> |
<%= link_to 'Back', races_path %>

app/views/races/index.html.erb
<div class="page-header">
  <h1>Kalender</h1>
</div>
<br/>
<table class="zebra-striped">
  <thead>
    <tr>
      <th>Naam</th>
      <th>Datum</th>
      <th>Categorie</th>
      <th>Vorige winnaar</th>
    </tr>
  </thead>
  <tbody>
  <% @races.each do |race| %>
    <tr>
      <td><%= race.name %></td>
      <td><%= l race.date.to_date, :format => :short %><%= " - #{l(race.end_date.to_date, :format => :short)}" if race.is_tour %></td>
      <td><%= race.category.name %></td>
      <td><%= race.previous_winner %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'New Race', new_race_path if (current_user and current_user.admin?)%>

app/views/races/new.html.erb
<h1>New race</h1>

<%= render 'form' %>

<%= link_to 'Back', races_path %>

app/views/races/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @race.name %>
</p>

<p>
  <b>Date:</b>
  <%= @race.date %>
</p>

<p>
  <b>End date:</b>
  <%= @race.end_date %>
</p>

<p>
  <b>Is tour:</b>
  <%= @race.is_tour %>
</p>

<p>
  <b>Previous winner:</b>
  <%= @race.previous_winner %>
</p>

<p>
  <b>Race:</b>
  <%= @race.race_id %>
</p>

<p>
  <b>Category:</b>
  <%= @race.category_id %>
</p>

<p>
  <b>Results ready:</b>
  <%= @race.results_ready %>
</p>

<p>
  <b>Team time trial:</b>
  <%= @race.team_time_trial %>
</p>


<%= link_to 'Edit', edit_race_path(@race) %> |
<%= link_to 'Back', races_path %>