config/routes.rb
Megatombike::Application.routes.draw do
  get "mobile_version" => "subscribe#force_mobile"
  get "full_version" => "subscribe#force_full"

  get "payments" => "payments#index"
  post "payments/set_paid/:team_id" => "payments#set_paid"
  post "payments/set_unpaid/:team_id" => "payments#set_unpaid"

  get "results/new" => "results#new"
  get "authentications" => "authentication#index"
  delete "authentications/:id" => "authentication#destroy"
  match "auth/:provider/callback" => "authentication#create"
  match "auth/failure" => "authentication#failure"
  post "authentications/use_this" => "authentication#use_this"

  post "results/create/:race_id" => "results#create"
  get "results/:race_id" => "results#index"
  get "results" => "results#index"
  
  resources :my_teams, :only => [:index]
  get "my_teams/:team_id/race/:race_id" => "my_teams#show"
  get "my_teams/:team_id" => "my_teams#show"

  get "teams/filter_period/:period_id" => "teams#filter_period"

  post "race_teams/add_rider"
  post "race_teams/remove_rider"
  post "race_teams/update_chosen"
 
  match "race_teams/new/:team_id/race/:race_id/:rdtmt" => "race_teams#new", :via => :get
  match "race_teams/new/:team_id/race/:race_id" => "race_teams#new", :via => :get
  match "race_teams/:team_id/race/:race_id/:rdtmt" => "race_teams#create", :via => :post
  match "race_teams/:team_id/race/:race_id" => "race_teams#create", :via => :post

  resources :race_teams, :only => [:edit,:update,:index, :destroy]
  resources :categories
  resources :races

  get "teams/filter_twt"
  get "teams/filter_fb"
  post "teams/add_rider"
  post "teams/remove_rider"

  post "riders/result_search"
  post "riders/search"
  get "subscribe/index"
  get "subscribe/finished"
  get "subscribe/reglement"

  resources :riders
  resources :cycling_teams
  resources :teams, :only => [:index, :new, :create, :destroy, :show]

  devise_for :users, :controllers => { :registrations => "registrations" }

  root :to => 'subscribe#index'

end

app/models/race_team.rb
class RaceTeam < ActiveRecord::Base
  MAXIMUM_SIZE = 10

  belongs_to :race
  belongs_to :team
  belongs_to :user
  has_and_belongs_to_many :riders

  validates :riders, :length => {:is => MAXIMUM_SIZE}

  def opposite
    team_riders = team.riders
    opposite = RaceTeam.new(:race_id => self.race_id, :team_id => self.team_id)
    opposite.riders = team_riders.reject { |rider| self.riders.include?(rider) }
    opposite
  end
  
  def self.exists_for_race(race_teams,race)
    race_team = race_teams.select { |rt| rt.race_id == race.id }.first
    if race_team.nil?
      race_team = race_teams.select { |rt| rt.race.date < race.date }.sort { |x,y| y.race.date <=> x.race.date }.first
      return race_team.nil? ? false : true
    else
      return true
    end
  end

  def self.get_by_team_and_race(team,race)
    race_team = RaceTeam.where(race_id: race.id, team_id: team.id).limit(1).first
    if race_team.nil?
      race_team = RaceTeam.where("team_id = :team_id AND races.date < :date",
                          {:team_id => team.id, :date => race.date})
                          .joins(:race).order("races.date DESC").limit(1).first
      return nil if race_team.nil?
      race_team = race_team.load_dependencies
      race_team = race_team.opposite unless race.possible_to_make_race_team_without_date_check(Race.all_except_stages, team.race_teams)
    else
      race_team = race_team.load_dependencies
    end
    race_team
  end

  def load_dependencies
    return RaceTeam.where(id: id).includes(:riders).limit(1).first
  end
end

app/controllers/race_teams_controller.rb
class RaceTeamsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin, :only => [:index,:destroy]

  # GET /race_teams
  # GET /race_teams.json
  def index
    @race_teams = RaceTeam.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @race_teams }
    end
  end

  # GET /race_teams/new/1/race/2
  # GET /race_teams/new/1/race/2.json
  def new
    @redirect_to_my_teams = !params[:rdtmt].nil? ? "/rdtmt" : ""
    @team = Team.where(id: params[:team_id], user_id: current_user.id).limit(1).first
    if @team.nil?
      not_allowed_to_view; return false;
    end
    @race = Race.find(params[:race_id])
    unless @race.possible_to_make_race_team(Race.all_except_stages, @team.race_teams)
      redirect_to :back, :alert => "Je kan voor deze wedstrijd geen ploeg meer aanmaken"
      return false
    end
    @race_team = RaceTeam.new(:team_id => @team.id, :race_id => @race.id)
    @selected_riders = []
    @selected_riders_ids = []
    respond_to do |format|
      format.mobile
      format.html # new.html.erb
      format.json { render json: @race_team }
    end
  end

  # GET /race_teams/1/edit
  def edit
    @race_team = RaceTeam.find(params[:id])
    @team = @race_team.team
    unless @team.user == current_user
      not_allowed_to_view; return false;
    end
    @race = @race_team.race
    unless @race.possible_to_make_race_team(Race.all_except_stages, @team.race_teams)
      redirect_to :back, :alert => "Je kan deze wedstrijdploeg niet meer wijzigen"
      return false
    end 
    @selected_riders = @race_team.riders
    @selected_riders_ids = @selected_riders.collect { |rider| rider.id }
  end

  # POST /race_teams/1/race/2
  # POST /race_teams/1/race/2.json
  def create
    @redirect_to_my_teams = !params[:rdtmt].nil? ? "/rdtmt" : ""
    @race_team = RaceTeam.new(:team_id => params[:team_id],
                              :race_id => params[:race_id])
    unless Team.find(params[:team_id]).user == current_user
      not_allowed_to_view; return false;
    end
    @race = Race.find(params[:race_id])
    @team = Team.find(params[:team_id])
    unless @race.possible_to_make_race_team(Race.all_except_stages, @team.race_teams)
      redirect_to :root, :alert => "Je kan voor deze wedstrijd geen ploeg meer aanmaken"
      return false
    end
    @race_team.riders = make_selection(params[:race_team])
    @selected_riders = @race_team.riders
    @selected_riders_ids = @selected_riders.collect { |rider| rider.id }
    respond_to do |format|
      if @race_team.save
        format.mobile {
          if @redirect_to_my_teams == "/rdtmt"
            redirect_to "/my_teams/#{@race_team.team_id}/race/#{@race_team.race_id}",
                        notice: 'Wedstrijdploeg is met succes aangemaakt.'
          else
            redirect_to '/subscribe/finished', 
                        notice: 'Wedstrijdploeg is met succes aangemaakt.' 
          end
        } 
        format.html { 
          if @redirect_to_my_teams == "/rdtmt"
            redirect_to "/my_teams/#{@race_team.team_id}/race/#{@race_team.race_id}",
                        notice: 'Wedstrijdploeg is met succes aangemaakt.'
          else
            redirect_to '/subscribe/finished', 
                        notice: 'Wedstrijdploeg is met succes aangemaakt.' 
          end
        }
        format.json { render json: @race_team, status: :created, location: @race_team }
      else
        format.mobile { render action: "new" }
        format.html { render action: "new" }
        format.json { render json: @race_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /race_teams/1
  # PUT /race_teams/1.json
  def update
    @race_team = RaceTeam.find(params[:id])
    unless @race_team.team.user == current_user
      not_allowed_to_view; return false;
    end
    @race = @race_team.race
    @team = @race_team.team
    unless @race.possible_to_make_race_team(Race.all_except_stages, @team.race_teams)
      redirect_to :root, :alert => "Je kan deze wedstrijdploeg niet meer wijzigen"
      return false
    end 
    @selected_riders = make_selection(params[:race_team])
    @selected_riders_ids = @selected_riders.collect { |rider| rider.id}
    respond_to do |format|
      if @race_team.update_attributes(:riders => @selected_riders)
        format.mobile { redirect_to "/my_teams/#{@race_team.team_id}/race/#{@race_team.race_id}", notice: 'De wedstrijdploeg is met succes gewijzigd.' }
        format.html { redirect_to "/my_teams/#{@race_team.team_id}/race/#{@race_team.race_id}", notice: 'De wedstrijdploeg is met succes gewijzigd.' }
        format.json { head :ok }
      else
        format.mobile { render action: "edit" }
        format.html { render action: "edit" }
        format.json { render json: @race_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /race_teams/1
  # DELETE /race_teams/1.json
  def destroy
    @race_team = RaceTeam.find(params[:id])
    @race_team.destroy
    respond_to do |format|
      format.html { redirect_to race_teams_url }
      format.json { head :ok }
    end
  end

  def add_rider
    @selected_riders = make_selection(params,"add")
    respond_to do |format|
      format.js { render "shared/update_selection", 
        :locals => {:team => "race_team", :riders_length => RaceTeam::MAXIMUM_SIZE}
      }
    end
  end

  def remove_rider
    @selected_riders = make_selection(params,"remove")
    respond_to do |format|
      format.js { render "shared/update_selection", 
        :locals => {:team => "race_team", :riders_length => RaceTeam::MAXIMUM_SIZE}
      }
    end
  end

  def update_chosen
    @team = Team.find(params[:team_id])
    @selected_riders_ids = []
    params[:riders].each { |val| @selected_riders_ids << val.to_i } unless params[:riders].nil?

    respond_to do |format|
      format.js
    end 
  end 
  
  private
  def make_selection(params, add_or_remove = "")
    riders_ids = []
    riders_ids = convert_string_array_to_int_array(params[:riders]) unless params[:riders].nil?
    rider_id = convert_string_to_int(params[:rider_id]) unless params[:rider_id].nil?
    if add_or_remove == "add"
      riders_ids << rider_id unless (riders_ids.include?(rider_id) or riders_ids.length >= RaceTeam::MAXIMUM_SIZE)
    elsif add_or_remove == "remove"
      riders_ids.delete(rider_id) if riders_ids.include?(rider_id)
    end
    riders = Rider.where(:id => riders_ids).joins(:cycling_team).includes(:cycling_team).all
    return put_riders_in_correct_order(riders_ids,riders)
  end

  def put_riders_in_correct_order(riders_ids, riders)
    riders_in_correct_order =[]
    riders_ids.each do |rider_id|
      index = riders.index {|value| value.id == rider_id}
      riders_in_correct_order << riders[index]
    end
    riders_in_correct_order
  end

  def convert_string_array_to_int_array(string_array)
    string_array.collect { |str| convert_string_to_int(str)}
  end

  def convert_string_to_int(str)
    str.to_i
  end

end

app/helpers/race_teams_helper.rb
module RaceTeamsHelper
end

app/views/race_teams/_form.html.erb
<%= form_for @race_team, :url => url do |f| %>
  <%= render :partial => "shared/validation_errors", :locals => {:model => @race_team} %> 

  <%= f.hidden_field :team_id %>
  <%= f.hidden_field :race_id %>

  <div class="row">
    <div class="span9">
      <div id="selected_riders">
        <%= render :partial => "riders/selected", 
              :locals => {:team => "race_team", :riders_length => RaceTeam::MAXIMUM_SIZE} %>
     </div>
    </div>
    <div class="span7">
      <div id="all_riders">
        <%= render :partial => "riders/choose", 
              :locals => {:riders => @team.riders, :team => "race_team"} %>  
      </div>
   </div>
  </div>
  <div class="actions">
    <%= f.submit "Verder", :class => 'btn primary' %>
    <%= f.submit "Maak leeg", :type => :reset, :class => 'btn' %>
  </div>
<% end %>

app/views/race_teams/_form.mobile.erb
<% content_for :mobile_back do %>
  <%= link_to "Terug", "/my_teams/#{@team.id}/race/#{@race.id}", :class => 'ui-btn-left', 'data-role' => 'button', 'data-mini' => 'true', 'data-icon' => 'arrow-l', 'data-iconpos' => 'notext' %>
<% end %>
<%= form_for @race_team, :url => url do |f| %>
  <%= render :partial => "shared/validation_errors", :locals => {:model => @race_team} %> 

  <%= f.hidden_field :team_id %>
  <%= f.hidden_field :race_id %>

  <div data-role="controlgroup">
    <% @team.riders.each_with_index do |rider,index| %>
      <% selected = @selected_riders_ids.include?(rider.id) ? true : false %> 
      <%= label_tag "race_team_riders_#{index}", rider.name %>
      <%= check_box_tag "race_team[riders][]", rider.id, selected , {:id => "race_team_riders_#{index}"} %> 
    <% end %>
  </div>

 <div class="actions">
    <%= f.submit "Verder" %>
  </div>
<% end %>
<%= content_for :mobile_fixed_footer do %>
    <div data-role="footer" data-position="fixed" data-theme="e">
      <h1><span id="nr_of_selected_riders"><%= @selected_riders_ids.length %></span> renners in selectie</h1>
    </div>
<% end %>

app/views/race_teams/edit.html.erb
<div class="page-header">
  <h1>Wijzig je wedstrijdploeg <small>voor <%= @race_team.race.name %></small></h1>
</div>

<%= render :partial => 'form', :locals => {:url => "/race_teams/#{@race_team.id}"} %>

<%= link_to 'Back', race_teams_path %>

app/views/race_teams/edit.mobile.erb
<h3><%= @race_team.race.name %></h3>
<%= render :partial => 'form', :locals => {:url => "/race_teams/#{@race_team.id}"} %>

app/views/race_teams/index.html.erb
<h1>Listing race_teams</h1>

<table>
  <tr>
    <th>Race</th>
    <th>Team</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @race_teams.each do |race_team| %>
  <tr>
    <td><%= race_team.race_id %></td>
    <td><%= race_team.team_id %></td>
    <td><%= link_to 'Show', race_team %></td>
    <td><%= link_to 'Edit', edit_race_team_path(race_team) %></td>
    <td><%= link_to 'Destroy', race_team, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/race_teams/new.html.erb
<div class="page-header">
  <h1>Maak een wedstrijdploeg aan <small>voor <%= @race_team.race.name %></small></h1>
</div>

<%= render  :partial => 'form', 
            :locals => {:url => "/race_teams/#{@race_team.team_id}/race/#{@race_team.race_id}#{@redirect_to_my_teams}"} %>

app/views/race_teams/new.mobile.erb
<h3><%= @race_team.race.name %></h3>
<%= render  :partial => 'form', 
            :locals => {:url => "/race_teams/#{@race_team.team_id}/race/#{@race_team.race_id}#{@redirect_to_my_teams}"} %>

app/views/race_teams/update_chosen.js.erb
$("#all_riders").html("<%= escape_javascript(render(:partial => 'riders/choose', :locals => {:riders => @team.riders, :team => "race_team"}))%>");