config/routes.rb
Megatombike::Application.routes.draw do
  get "mobile_version" => "subscribe#force_mobile"
  get "full_version" => "subscribe#force_full"

  get "payments" => "payments#index"
  post "payments/set_paid/:team_id" => "payments#set_paid"
  post "payments/set_unpaid/:team_id" => "payments#set_unpaid"

  get "results/new" => "results#new"
  get "authentications" => "authentication#index"
  delete "authentications/:id" => "authentication#destroy"
  match "auth/:provider/callback" => "authentication#create"
  match "auth/failure" => "authentication#failure"
  post "authentications/use_this" => "authentication#use_this"

  post "results/create/:race_id" => "results#create"
  get "results/:race_id" => "results#index"
  get "results" => "results#index"
  
  resources :my_teams, :only => [:index]
  get "my_teams/:team_id/race/:race_id" => "my_teams#show"
  get "my_teams/:team_id" => "my_teams#show"

  get "teams/filter_period/:period_id" => "teams#filter_period"

  post "race_teams/add_rider"
  post "race_teams/remove_rider"
  post "race_teams/update_chosen"
 
  match "race_teams/new/:team_id/race/:race_id/:rdtmt" => "race_teams#new", :via => :get
  match "race_teams/new/:team_id/race/:race_id" => "race_teams#new", :via => :get
  match "race_teams/:team_id/race/:race_id/:rdtmt" => "race_teams#create", :via => :post
  match "race_teams/:team_id/race/:race_id" => "race_teams#create", :via => :post

  resources :race_teams, :only => [:edit,:update,:index, :destroy]
  resources :categories
  resources :races

  get "teams/filter_twt"
  get "teams/filter_fb"
  post "teams/add_rider"
  post "teams/remove_rider"

  post "riders/result_search"
  post "riders/search"
  get "subscribe/index"
  get "subscribe/finished"
  get "subscribe/reglement"

  resources :riders
  resources :cycling_teams
  resources :teams, :only => [:index, :new, :create, :destroy, :show]

  devise_for :users, :controllers => { :registrations => "registrations" }

  root :to => 'subscribe#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :races
  validates :name, :presence => true
  validates :nr_of_riders, :presence => true 
  validates :points, :presence => true
  
  def points_array
    points.split("/").collect! { |point| point.to_i }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <%= render :partial => "shared/validation_errors", :locals => {:model => @category} %> 

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :nr_of_riders %><br />
    <%= f.number_field :nr_of_riders %>
  </div>
  <div class="field">
    <%= f.label :points %><br />
    <%= f.number_field :points %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<table class="bordered-table zebra-striped">
  <thead>
    <th>Categorie</th>
    <th># Beloonde renners</th>
    <th>Puntenverdeling</th>
  </thead>
  <tbody>
<% Category.all.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.nr_of_riders %></td>
    <td><%= category.points %></td>
  </tr>
<% end %>
</tbody>
</table>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Nr of riders:</b>
  <%= @category.nr_of_riders %>
</p>

<p>
  <b>Points:</b>
  <%= @category.points %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>